# Generated by Django 5.1.3 on 2024-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='email',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='password',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
