# Generated by Django 5.1.3 on 2024-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customermodel_email_customermodel_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='name',
            new_name='username',
        ),
    ]
