# Generated by Django 5.1.3 on 2024-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_name_customermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='cpassword',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
