# Generated by Django 5.1.3 on 2024-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='user',
        ),
    ]
